name: spatial_card_example
description: Demonstrates the features of the spatial_card package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0-86.0.dev
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  spatial_card:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
